### ISSUE TITLE
Issue in line 302, identities

### ISSUE THREAD

**Issue by hestmo** [soren-cloud/ExO-EnableMailboxAuditLogging#1]
Hi Søren,

Amazing job as always.
There however seem to be an issue with the Set-Mailbox command.
In the script the Mailbox object is piped to the set command, this makes the script use the identity parameter on the object per default.

An issue arises if two users has the same Display Name as their Identity will be identical will thus error on them as the user cannot be set.

I recommend simply forcing the use of Identity to be **-Identity $Mailbox.UserPrincipalName**
```

Set-Mailbox -Identity $Mailbox.UserPrincipalName -AuditEnabled $true -AuditOwner $AuditOwner -AuditAdmin $AuditAdmin -AuditDelegate $AuditDelegate `
            -AuditLogAgeLimit $AuditLogAgeLimit -Force
```

**Error for reference** 
_The operation couldn't be performed because 'DisplayName of User' matches multiple entries.
    + CategoryInfo          : NotSpecified: (:) [Set-Mailbox], ManagementObjectAmbiguousException
    + FullyQualifiedErrorId : [Server=AM5P189MB0530,RequestId=383ccbd6-3eae-4fed-83ba-af417e52d1e4,TimeStamp=5/23/2018 
9:14:30 AM] [FailureCategory=Cmdlet-ManagementObjectAmbiguousException] 
C5534BE8,Microsoft.Exchange.Management.RecipientTasks.SetMailbox
    + PSComputerName        : outlook.office365.com_

**Comment by soren-cloud** [comment]
Changed the Set-Mailbox command as described.

Thx mate.
